JoinPlan/Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JoinPlan.DAL;
using JoinPlan.Models;

namespace JoinPlan.Controllers
{
    public class ActivityController : Controller
    {
        private JoinPlanContext db = new JoinPlanContext();

        // GET: Activity
        public ActionResult Index()
        {
            return View(db.Activities.ToList());
        }

        // GET: Activity/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // GET: Activity/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Activity/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ActivityID,Name,Description,ImageUrl,OrganizerEmail,ActivityDateTime,MaxParticipant")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                db.Activities.Add(activity);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(activity);
        }

        // GET: Activity/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // POST: Activity/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ActivityID,Name,Description,ImageUrl,OrganizerEmail,ActivityDateTime,MaxParticipant")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(activity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(activity);
        }

        // GET: Activity/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // POST: Activity/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Activity activity = db.Activities.Find(id);
            db.Activities.Remove(activity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JoinPlan/Controllers/CMSController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JoinPlan.DAL;
using JoinPlan.Models;

namespace JoinPlan.Controllers
{
    public class CMSController : Controller
    {
        private JoinPlanContext db = new JoinPlanContext();

        // GET: CMS
        public ActionResult Index()
        {
            return View(db.CMS.ToList());
        }

        // GET: CMS/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CMS cMS = db.CMS.Find(id);
            if (cMS == null)
            {
                return HttpNotFound();
            }
            return View(cMS);
        }

        // GET: CMS/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CMS/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CmsID,Name,Value,Type")] CMS cMS)
        {
            if (ModelState.IsValid)
            {
                db.CMS.Add(cMS);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cMS);
        }

        // GET: CMS/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CMS cMS = db.CMS.Find(id);
            if (cMS == null)
            {
                return HttpNotFound();
            }
            return View(cMS);
        }

        // POST: CMS/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CmsID,Name,Value,Type")] CMS cMS)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cMS).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cMS);
        }

        // GET: CMS/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CMS cMS = db.CMS.Find(id);
            if (cMS == null)
            {
                return HttpNotFound();
            }
            return View(cMS);
        }

        // POST: CMS/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CMS cMS = db.CMS.Find(id);
            db.CMS.Remove(cMS);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JoinPlan/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JoinPlan.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Activities()
        {
            ViewBag.Message = "Your activities page.";

            return View();
        }
    }
}

JoinPlan/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

JoinPlan/Views/Home/Activities.cshtml
@{
    ViewBag.Title = "Activities";
}

@*<h3>@ViewBag.Title</h3>*@

@if (Request.IsAuthenticated)
{
    if (User.IsInRole("admin"))
    {
        @Html.ActionLink("Manage Activities", "Index", "Activity")
    }
}
<hr />
@*<h3>@ViewBag.Message</h3>*@

<div class="d-flex justify-content-start" style="margin-bottom:2rem;">
    <div class="dropdown">
        <button onclick="myFunction()" class="dropbtn"> Search&nbsp;&nbsp;<i class="fa fa-search" aria-hidden="true"></i> </button>
        <div id="myDropdown" class="dropdown-content">
            <input type="text" placeholder="Search.." id="myInput" onkeyup="filterFunction()">
        </div>
    </div>
</div>


<h4>Upcoming activities</h4>
<div class="row" id="future-activ-ls">
    <div class="col-lg-12"><p>Loading activities...</p></div>

</div>

<h4>Past activities</h4>
<div class="row" id="past-activ-ls">
    <div class="col-lg-12"><p>Loading activities...</p></div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/moment")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryajax")

    <script type="text/javascript">
        $(function () {
            $.ajax({
                type: 'GET',
                url: '/api/Activities',
                data: { futureDated: true },
                success: function (result) {
                    //console.log('Coming activities:');
                    if (result.length > 0) {

                        $("#future-activ-ls").empty();
                        //var elemsList = [];
                        $.each(result, function (i, activity) {
                            try {
                                //console.log(activity.Name);
                                var cardHtml =
                                    `<div class="col-md-4" style="padding:1rem">
                                                <div class="card">
                                                    <div class="card-img-top" style="height:170px">
                                                        <img style="width:100%; max-height:170px" src="${activity.ImageUrl}" alt="${activity.Name}">
                                                    </div>
                                                    <div class="card-body">
                                                        <h5>${activity.Name}</h5>
                                                        <i>${moment(activity.ActivityDateTime).format("YYYY-MM-DD hh:mm A")}</i>
                                                        <p style="text-overflow: ellipsis;white-space: nowrap;overflow: hidden;">${activity.Description}</p>
                                                        <p >${activity.Participations.length}/ ${activity.MaxParticipant} participants</p>
                                                        <a href="/Activity/Details/${activity.ActivityID}" class="btn btn-primary">View details</a>
                                                    </div>
                                                </div>
                                            </div>`
                                //elemsList.push(cardHtml);
                                $("#future-activ-ls").append(cardHtml);
                                $('#myDropdown').append(`<a href="/Activity/Details/${activity.ActivityID}">${activity.Name}</a>`)
                            } catch (err) {
                                console.log(err);
                            }
                        });

                    } else {
                        $("#future-activ-ls").append(`<div class="col-lg-12"><p>No future activities.</p></div>`);
                    }
                },
            });
            $.ajax({
                type: 'GET',
                url: '/api/Activities',
                data: { futureDated: false },
                success: function (result) {
                    //console.log('Past activities:');
                    if (result.length > 0) {

                        $("#past-activ-ls").empty();
                        //var elemsList = [];
                        $.each(result, function (i, activity) {
                            try {
                                //console.log(activity.Name);
                                var cardHtml =
                                    `<div class="col-md-4" style="padding:1rem">
                                                <div class="card">
                                                    <div class="card-img-top" style="height:170px">
                                                        <img style="width:100%; max-height:170px" src="${activity.ImageUrl}" alt="${activity.Name}">
                                                    </div>
                                                    <div class="card-body">
                                                        <h5>${activity.Name}</h5>
                                                        <i>${moment(activity.ActivityDateTime).format("YYYY-MM-DD hh:mm A")}</i>
                                                        <p style="text-overflow: ellipsis;white-space: nowrap;overflow: hidden;">${activity.Description}</p>
                                                        <p >${activity.Participations.length}/ ${activity.MaxParticipant} participants</p>
                                                        <a href="/Activity/Details/${activity.ActivityID}" class="btn btn-primary">View details</a>
                                                    </div>
                                                </div>
                                            </div>`
                                //elemsList.push(cardHtml);
                                $("#past-activ-ls").append(cardHtml);
                                $('#myDropdown').append(`<a href="/Activity/Details/${activity.ActivityID}">${activity.Name}</a>`)
                            } catch (err) {
                                console.log(err);
                            }
                        });

                    } else {
                        $("#past-activ-ls").append(`<div class="col-lg-12"><p>No past activities.</p></div>`);
                    }
                },
            });
        });

    </script>

    <script>
        /* When the user clicks on the button,
        toggle between hiding and showing the dropdown content */
        function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
        }

        function filterFunction() {
            var input, filter, ul, li, a, i;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            div = document.getElementById("myDropdown");
            a = div.getElementsByTagName("a");
            for (i = 0; i < a.length; i++) {
                txtValue = a[i].textContent || a[i].innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    a[i].style.display = "";
                } else {
                    a[i].style.display = "none";
                }
            }
        }
    </script>
}

JoinPlan/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

JoinPlan/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@if (Request.IsAuthenticated)
{
    if (User.IsInRole("admin"))
    {
        @Html.ActionLink("Manage Site Content", "Index", "CMS")

        <hr />
    }
}
<div class="jumbotron" id="lhb">
    <h1>JoinPlan</h1>
    <p class="lead" id="ht">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="@Url.Action("Activities","Home")" class="btn btn-primary btn-lg">View all activities &raquo;</a></p>
</div>

<div class="text-center">
    <h3>About us</h3>
    <br />
    <p id="abt"></p>
    <br />
    <p id="abjp"></p>
    <br />
</div>
<hr />
<div class="row d-flex justify-content-center">
    <h3>Coming activities</h3>
</div>

<div class="row" id="future-activ-ls">
    <div class="col-lg-12"><p>Loading activities...</p></div>
</div>
<div class="d-flex justify-content-center">
    <a href="@Url.Action("Activities","Home")" class="btn btn-outline-primary">
        View all activities
    </a>
</div>
<br />
<hr />
<div class="text-center">
    <h3>Contact Us</h3>
    <br />
    <div class="d-flex justify-content-center">
        <a id="fb-link" href="" target="_blank">
            <img src="~/Content/images/facebook.png" class="social-media-icon" style="margin-right:2.5rem" />
        </a>
        <a id="tw-link" href="" target="_blank">
            <img src="~/Content/images/twitter.png" target="_blank" class="social-media-icon" style="margin-right:2.5rem" />
        </a>
        <a id="ig-link" href="" target="_blank">
            <img src="~/Content/images/instagram.png" target="_blank" class="social-media-icon" style="margin-right:0" />
        </a>
    </div>
    <br />
    <a href="@Url.Action("Register", "Account")" class="btn btn-primary btn-lg">
        Register Now
    </a>
    <br />
</div>
<br /> <br />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/moment")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryajax")

    <script type="text/javascript">
        $(function () {

            $.ajax({
                type: 'GET',
                url: '/api/CMS1',
                data: { futureDated: true },
                success: function (result) {
                    $.each(result, function (i, cmsData) {
                        switch (cmsData.Name) {
                            case 'LANDING_BANNER_BG':
                                $('#lhb').css('background-image', 'url(' + cmsData.Value + ')');
                                $('#lhb').css('color', 'white');
                                $('#lhb').css('height', '370px');
                                break;
                            case 'LANDING_HEADER':
                                $('#ht').html(cmsData.Value);
                                break;
                            case 'ABOUT_TEAM':
                                $('#abt').html(cmsData.Value);
                                break;
                            case 'ABOUT_JP':
                                $('#abjp').html(cmsData.Value);
                                break;
                            case 'FB_LINK':
                                $('#fb-link').attr('href', cmsData.Value);
                                break;
                            case 'TW_LINK':
                                $('#tw-link').attr('href', cmsData.Value);
                                break;
                            case 'IG_LINK':
                                $('#ig-link').attr('href', cmsData.Value);
                                break;
                        }
                    });
                }
            });

            $.ajax({
                type: 'GET',
                url: '/api/Activities',
                data: { futureDated: true },
                success: function (result) {
                    //console.log('Coming activities:');
                    if (result.length > 0) {

                        $("#future-activ-ls").empty();
                        //var elemsList = [];
                        $.each(result, function (i, activity) {
                            try {
                                //console.log(activity.Name);
                                var cardHtml =
                                    `<div class="col-md-4" style="padding:1rem">
                                                                <div class="card">
                                                                    <div class="card-img-top" style="height:170px">
                                                                        <img style="width:100%; max-height:170px" src="${activity.ImageUrl}" alt="${activity.Name}">
                                                                    </div>
                                                                    <div class="card-body">
                                                                        <h5>${activity.Name}</h5>
                                                                        <i>${moment(activity.ActivityDateTime).format("YYYY-MM-DD hh:mm A")}</i>
                                                                        <p style="text-overflow: ellipsis;white-space: nowrap;overflow: hidden;">${activity.Description}</p>
                                                                        <p >${activity.Participations.length}/ ${activity.MaxParticipant} participants</p>
                                                                        <a href="/Activity/Details/${activity.ActivityID}" class="btn btn-primary">View details</a>
                                                                    </div>
                                                                </div>
                                                            </div>`
                                //elemsList.push(cardHtml);
                                $("#future-activ-ls").append(cardHtml);
                                $('#myDropdown').append(`<a href="/Activity/Details/${activity.ActivityID}">${activity.Name}</a>`)
                            } catch (err) {
                                console.log(err);
                            }
                        });

                    } else {
                        $("#future-activ-ls").append(`<div class="col-lg-12"><p>No future activities.</p></div>`);
                    }
                },
            });
        });

    </script>

}